"use client";

import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    nav_projects: 'Projects',
    nav_about: 'About',
    nav_skills: 'Skills',
    nav_contact: 'Contact',
    hero_title: 'Freelance Smart Contract & Web3 Developer | Solana & Ethereum | SAP Techno-Functional',
    hero_subtitle: 'Passionate Freelance Developer specialized in Smart Contracts (Rust, Solidity, Anchor) and blockchain architecture. Engineering decentralized protocols with a focus on security and scalability.',
    hero_cta_projects: 'View Projects',
    hero_cta_contact: 'Contact Me',
    about_title: 'About Me',
    about_text: 'I am a Web3-focused freelance developer passionate about building decentralized protocols and high-performance tooling. My experience spans from writing Solana smart contracts in Rust (Anchor) to developing robust SDKs and wallet-tracking systems. I am currently expanding my expertise into the Ethereum ecosystem with Solidity and Hardhat, driven by a builder mindset and a passion for protocol-level innovation.',
    skills_title: 'Technical Skills',
    skills_solana: 'Web3 / Solana',
    skills_ethereum: 'Ethereum EVM',
    skills_frontend: 'Frontend Development',
    skills_backend: 'Backend / General',
    skills_sap: 'SAP Technologies',
    skills_learning: 'In Progress',
    skills_started_january: 'Started in early January',
    projects_title: 'Featured Projects',
    projects_view_more: 'View More',
    projects_view_less: 'Show Less',
    experience_title: 'Specialization & Work with us',
    contact_title: 'Get In Touch',
    contact_name: 'Name',
    contact_email: 'Email',
    contact_message: 'Message',
    contact_send: 'Send Message',
    footer_rights: 'All rights reserved.',
    nav_download_cv: 'Download CV',
    sap_future: 'Future SAP Project Manager',
    github_url: 'https://github.com/aldino666',
    linkedin_url: 'https://www.linkedin.com/in/ramanantsirahonana/',
    about_subtitle: 'Building at the intersection of technical depth and decentralized innovation.',
    about_approach: 'I prioritize hands-on experimentation and deep protocol understanding. From crafting developer SDKs to analyzing on-chain data, I build with a focus on scalability, clean architecture, and cross-chain capabilities.',
    spec_web_title: 'Core Development',
    spec_web_desc: 'Crafting modern, high-performance applications with TypeScript and modern frameworks.',
    spec_web3_title: 'Web3 / Blockchain',
    spec_web3_desc: 'Specializing in Solana (Rust/Anchor) and expanding into Ethereum (Solidity/Hardhat).',
    spec_sap_title: 'SAP Ecosystem',
    spec_sap_desc: 'Enterprise integration and future-ready SAP project management.',
    skills_subtitle: 'My technical toolkit across different domains.',
    projects_subtitle: 'A selection of my recent work in Web, Web3, and Enterprise solutions.',
    proj_dapp_title: 'ox-amm-pool',
    proj_dapp_desc: 'Decentralized automated market maker for liquidity provision on Solana, designed for efficient and secure token swaps.',
    proj_smart_title: 'Oxalix Smart Contract',
    proj_smart_desc: 'Custom Rust-based smart contract for the Oxalix ecosystem, focusing on security, scalability, and optimized resource management.',
    proj_data_title: 'Wallet Tracking Solana',
    proj_data_desc: 'High-performance tool for real-time tracking of wallet activities and deep decoding of transaction signatures on the Solana blockchain.',
    proj_token_title: 'Oxalix Token Creator',
    proj_token_desc: 'Automated on-chain token creation platform on Solana, simplifying the deployment process for builders.',
    proj_sdk_title: 'Oxalix Presales SDK',
    proj_sdk_desc: 'Comprehensive TypeScript SDK for seamless integration of presale mechanics into dApps, focused on developer experience.',
    proj_chaintip_title: 'CHAINTIP - GASLESS TIPS (ERC-4337) - [ In Progress ]',
    proj_chaintip_desc: 'Development of a decentralized tipping platform using account abstraction (ERC-4337).',
    proj_fiori_title: 'Fiori-V1 (SAP)',
    proj_fiori_desc: 'Modern purchase order management system built with SAP Fiori standards, demonstrating enterprise-grade UX and workflow logic.',
    proj_ecommerce_title: 'E-Commerce Platform',
    proj_ecommerce_content: 'Full-stack sales platform with a complete back-office, showcasing robust architecture and scalable database management.',
    proj_webmapping_title: 'Webmapping & Spatial Analysis',
    proj_webmapping_desc: 'Spatial analysis tool for neighborhood mapping, evaluating geographic relationships between points of interest.',
    journey_subtitle: 'Web3 & SAP Journey',
    journey_sap_work_title: 'SAP ERP Training & Solutions',
    journey_sap_work_desc: 'Training and practical experience in SAP ERP solutions, covering both functional and technical aspects.',
    journey_sap_exp_title: 'SAP ERP expertise and development',
    journey_sap_exp_desc: 'Advanced technical and functional development within the SAP ecosystem.',
    journey_web3_title: 'Web3 Specialization & Development',
    journey_web3_desc: 'Specialization & work in Web3 development, with a focus on Solana smart contracts, decentralized applications (dApps), and blockchain systems.',
    journey_nomerikia_title: 'Full Stack Developer at Nomerikia.mg',
    journey_nomerikia_desc: 'Designed and implemented robust web solutions for diverse clients.',
    journey_health_title: 'Full Stack Web Developer Internship',
    journey_health_desc: 'Experience in the health sector building specialized web tools.',
    journey_edu_title: 'Degree in App Development & IT Management',
    journey_edu_desc: 'Comprehensive training in software engineering and information systems management.',
    contact_subtitle: 'Ready to discuss your next big project or an enterprise opportunity?',
    contact_connect: 'Connect with me',
    contact_sap_consultant: 'Need an SAP Techno-Functional Consultant?',
    contact_blockchain_expert: 'Future Blockchain Architect',
    available: 'Available for new projects',
    web3_interaction_title: 'Web3 Interaction',
    web3_interaction_subtitle: 'Support my work with a Solana donation. Demonstrate real-world blockchain capability.',
    wallet_connect: 'Connect Wallet',
    wallet_connected: 'Connected',
    wallet_not_connected: 'Not Connected',
    amount_placeholder: 'Amount (SOL)',
    send_button: 'Send SOL',
    status_pending: 'Transaction Pending...',
    status_success: 'Transaction Successful!',
    status_error: 'Transaction Failed',
    web3_support_title: 'Solana Support',
    web3_support_desc: 'This module serves as both a donation gateway and a live demonstration of my Web3 engineering capabilities. By connecting your wallet and executing a transaction, you can directly interact with the Solana blockchain through a secure, custom-built interface that showcases my expertise in wallet integration, smart contract interaction, and real-time on-chain data handling.',
    web3_view_explorer: 'View on Explorer',
    web3_connect_prompt: 'Please connect your wallet to interact',
    token_inspector_title: 'Token Inspector',
    token_inspector_subtitle: 'Analyze any Solana token to view its metadata and security status.',
    token_address_label: 'Token Mint Address',
    token_inspect_button: 'Inspect Token',
    token_loading: 'Fetching token data...',
    token_error: 'Invalid token address or network error',
    token_metadata: 'Metadata',
    token_security: 'Security Status',
    token_name: 'Token Name',
    token_supply: 'Total Supply',
    token_decimals: 'Decimals',
    token_mint_authority: 'Mint Authority',
    token_freeze_authority: 'Freeze Authority',
    token_update_authority: 'Update Authority',
    token_holders: 'Holders',
    token_volume_24h: '24h Volume',
    token_status_revoked: 'Revoked (Safe)',
    token_status_active: 'Active (Warning)',
    token_status_none: 'None',
    tx_confirming: 'Confirming transaction...',
    tx_success: 'Transaction successful!',
    tx_failed: 'Transaction failed',
    invalid_amount: 'Invalid amount',
    email_response_greeting: 'Hello,',
    email_response_thanks: 'Thank you for your message.',
    email_response_message: 'Thank you for your interest in my profile and projects. I will get back to you very soon with a detailed response.',
    email_response_crd: 'Best regards,',
  },
  fr: {
    nav_projects: 'Projets',
    nav_about: 'À Propos',
    nav_skills: 'Compétences',
    nav_contact: 'Contact',
    hero_title: 'Développeur Freelance Smart Contract & Web3 | Solana & Ethereum | Consultant Techno-Fonctionnel SAP',
    hero_subtitle: 'Développeur Freelance passionné par le développement de Smart Contracts (Rust, Solidity, Anchor) et l\'architecture blockchain. Ingénierie de protocoles décentralisés avec un focus sur la sécurité.',
    hero_cta_projects: 'Voir les Projets',
    hero_cta_contact: 'Me Contacter',
    about_title: 'À Propos de Moi',
    about_text: 'Je suis un développeur freelance axé sur le Web3, passionné par la construction de protocoles décentralisés et d\'outils haute performance. Mon expérience s\'étend de l\'écriture de contrats intelligents Solana en Rust (Anchor) au développement de SDK robustes et de systèmes de suivi de portefeuilles. J\'élargis actuellement mon expertise à l\'écosystème Ethereum avec Solidity et Hardhat, guidé par une mentalité de bâtisseur et une passion pour l\'innovation au niveau protocole.',
    skills_title: 'Compétences Techniques',
    skills_solana: 'Web3 / Solana',
    skills_ethereum: 'Ethereum EVM',
    skills_frontend: 'Développement Frontend',
    skills_backend: 'Backend / Général',
    skills_sap: 'Technologies SAP',
    skills_learning: 'En cours',
    skills_started_january: 'Débuté début janvier',
    projects_title: 'Projets Phares',
    projects_view_more: 'Voir Plus',
    projects_view_less: 'Voir Moins',
    experience_title: 'Spécialisation & Collaboration web 3',
    contact_title: 'Me Contacter',
    contact_name: 'Nom',
    contact_email: 'Email',
    contact_message: 'Message',
    contact_send: 'Envoyer',
    footer_rights: 'Tous droits réservés.',
    nav_download_cv: 'Télécharger le CV',
    sap_future: 'Futur Chef de Projet SAP',
    github_url: 'https://github.com/aldino666',
    linkedin_url: 'https://www.linkedin.com/in/ramanantsirahonana/',
    about_subtitle: 'Bâtir à l\'intersection de la profondeur technique et de l\'innovation décentralisée.',
    about_approach: 'Je privilégie l\'expérimentation pratique et la compréhension profonde des protocoles. De la conception de SDK pour développeurs à l\'analyse de données on-chain, je construis avec un focus sur la scalabilité, une architecture propre et des capacités multi-chaînes.',
    spec_web_title: 'Développement Core',
    spec_web_desc: 'Création d\'applications modernes et performantes avec TypeScript et des frameworks récents.',
    spec_web3_title: 'Web3 / Blockchain',
    spec_web3_desc: 'Spécialisé dans Solana (Rust/Anchor) et en expansion vers Ethereum (Solidity/Hardhat).',
    spec_sap_title: 'Écosystème SAP',
    spec_sap_desc: 'Intégration d\'entreprise et gestion de projet SAP tournée vers l\'avenir.',
    skills_subtitle: 'Ma boîte à outils technique dans différents domaines.',
    projects_subtitle: 'Une sélection de mes travaux récents en Web, Web3 et solutions d\'entreprise.',
    proj_dapp_title: 'ox-amm-pool',
    proj_dapp_desc: 'Market maker automatisé décentralisé pour la fourniture de liquidités sur Solana, conçu pour des échanges de jetons efficaces et sécurisés.',
    proj_smart_title: 'Oxalix Smart Contract',
    proj_smart_desc: 'Contrat intelligent Rust personnalisé pour l\'écosystème Oxalix, axé sur la sécurité, la scalabilité et la gestion optimisée des ressources.',
    proj_data_title: 'Wallet Tracking Solana',
    proj_data_desc: 'Outil haute performance pour le suivi en temps réel des activités de portefeuilles et le décodage approfondi des signatures de transaction sur Solana.',
    proj_token_title: 'Oxalix Token Creator',
    proj_token_desc: 'Plateforme de création automatisée de jetons sur Solana, simplifiant le processus de déploiement pour les bâtisseurs.',
    proj_sdk_title: 'Oxalix Presales SDK',
    proj_sdk_desc: 'SDK TypeScript complet pour une intégration fluide des mécaniques de prévente dans les dApps, axé sur l\'expérience développeur.',
    proj_chaintip_title: 'CHAINTIP - POURBOIRES SANS GAS (ERC-4337) - [ en cours ]',
    proj_chaintip_desc: 'Développement d’une plateforme de pourboires décentralisée utilisant l’abstraction de compte (ERC-4337).',
    proj_fiori_title: 'Fiori-V1 (SAP)',
    proj_fiori_desc: 'Système moderne de gestion des bons de commande construit selon les standards SAP Fiori, démontrant une UX d\'entreprise.',
    proj_ecommerce_title: 'Plateforme E-Commerce',
    proj_ecommerce_content: 'Plateforme de vente full-stack avec back-office complet, illustrant une architecture robuste et une gestion de base de données évolutive.',
    proj_webmapping_title: 'Webmapping & Analyse Spatiale',
    proj_webmapping_desc: 'Outil d\'analyse spatiale pour la cartographie de voisinage, évaluant les relations géographiques entre points d\'intérêt.',
    journey_subtitle: 'Parcours Web3 & SAP',
    journey_sap_work_title: 'Formation & Solutions SAP ERP',
    journey_sap_work_desc: 'Formation et expérience pratique des solutions SAP ERP, couvrant les aspects fonctionnels et techniques.',
    journey_sap_exp_title: 'Expertise et développement SAP ERP',
    journey_sap_exp_desc: 'Développement technique et fonctionnel avancé au sein de l\'écosystème SAP.',
    journey_web3_title: 'Spécialisation & Développement Web3',
    journey_web3_desc: 'Spécialisation et travail dans le développement Web3, avec un focus sur les contrats intelligents Solana, les dApps et les systèmes blockchain.',
    journey_nomerikia_title: 'Développeur Full Stack chez Nomerikia.mg',
    journey_nomerikia_desc: 'Conception et implémentation de solutions web robustes pour divers clients.',
    journey_health_title: 'Stage Développeur Web Fullstack',
    journey_health_desc: 'Expérience dans le domaine de la santé pour la création d\'outils web spécialisés.',
    journey_edu_title: 'Formation en développement d\'application et management informatique',
    journey_edu_desc: 'Cursus complet en ingénierie logicielle et gestion des systèmes d\'information.',
    contact_subtitle: 'Prêt à discuter de votre prochain grand projet ou d\'une opportunité en entreprise ?',
    contact_connect: 'Connectez avec moi',
    contact_sap_consultant: 'Besoin d\'un Consultant Techno-Fonctionnel SAP ?',
    contact_blockchain_expert: 'Futur Architecte Blockchain',
    available: 'Disponible pour de nouveaux projets',
    web3_interaction_title: 'Interaction Web3',
    web3_interaction_subtitle: 'Soutenez mon travail avec une donation Solana. Démonstration de capacité blockchain réelle.',
    wallet_connect: 'Connecter Portefeuille',
    wallet_connected: 'Connecté',
    wallet_not_connected: 'Non Connecté',
    amount_placeholder: 'Montant (SOL)',
    send_button: 'Envoyer SOL',
    status_pending: 'Transaction en cours...',
    status_success: 'Transaction réussie !',
    status_error: 'Échec de la transaction',
    web3_support_title: 'Support Solana',
    web3_support_desc: 'Ce module sert à la fois de passerelle de donation et de démonstration en direct de mes capacités d\'ingénierie Web3. En connectant votre portefeuille et en exécutant une transaction, vous interagissez directement avec la blockchain Solana via une interface sécurisée et personnalisée qui illustre mon expertise en intégration de portefeuilles, interaction avec les contrats intelligents et gestion des données on-chain en temps réel.',
    web3_view_explorer: 'Voir sur l\'Explorer',
    web3_connect_prompt: 'Veuillez connecter votre portefeuille pour interagir',
    token_inspector_title: 'Inspecteur de Jeton',
    token_inspector_subtitle: 'Analysez n\'importe quel jeton Solana pour voir ses métadonnées et son statut de sécurité.',
    token_address_label: 'Adresse du Jeton (Mint)',
    token_inspect_button: 'Inspecter le Jeton',
    token_loading: 'Récupération des données...',
    token_error: 'Adresse de jeton invalide ou erreur réseau',
    token_metadata: 'Métadonnées',
    token_security: 'Statut de Sécurité',
    token_name: 'Nom du Jeton',
    token_supply: 'Offre Totale',
    token_decimals: 'Décimales',
    token_mint_authority: 'Autorité de Frappe',
    token_freeze_authority: 'Autorité de Gel',
    token_update_authority: 'Autorité de Mise à Jour',
    token_holders: 'Détenteurs',
    token_volume_24h: 'Volume 24h',
    token_status_revoked: 'Révoquée (Sûr)',
    token_status_active: 'Active (Attention)',
    token_status_none: 'Aucune',
    tx_confirming: 'Confirmation de la transaction...',
    tx_success: 'Transaction réussie !',
    tx_failed: 'Échec de la transaction',
    invalid_amount: 'Montant invalide',
    email_response_greeting: 'Bonjour,',
    email_response_thanks: 'Merci pour votre message.',
    email_response_message: 'Je vous remercie pour votre intérêt concernant mon profil et mes projets. Je reviens vers vous très prochainement avec une réponse détaillée.',
    email_response_crd: 'Cordialement,',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
